//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public System.Guid ID { get; set; }
        public int NumberOfSurvey { get; set; }
        public int Number { get; set; }
        public string Recipient { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
