//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HakatonVEBEntities : DbContext
    {
        public HakatonVEBEntities()
            : base("name=HakatonVEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Access { get; set; }
        public virtual DbSet<ButtonsOfQuestions> ButtonsOfQuestions { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Survey> Survey { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
    }
}
